2019-01-19 13:14:34,535 ERROR: Exception on /notifications [GET] [in c:\users\spriy\documents\python_programs\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\spriy\documents\python_programs\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\spriy\documents\python_programs\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\spriy\documents\python_programs\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\spriy\documents\python_programs\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\spriy\documents\python_programs\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\spriy\documents\python_programs\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\spriy\documents\python_programs\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\spriy\Documents\Python_programs\microblog\app\routes.py", line 19, in notifications
    return jsonify([{
NameError: name 'jsonify' is not defined
2019-01-19 13:14:44,343 ERROR: Exception on /notifications [GET] [in c:\users\spriy\documents\python_programs\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\spriy\documents\python_programs\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\spriy\documents\python_programs\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\spriy\documents\python_programs\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\spriy\documents\python_programs\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\spriy\documents\python_programs\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\spriy\documents\python_programs\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\spriy\documents\python_programs\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\spriy\Documents\Python_programs\microblog\app\routes.py", line 19, in notifications
    return jsonify([{
NameError: name 'jsonify' is not defined
2019-01-19 13:14:56,804 INFO: Microblog startup [in C:\Users\spriy\Documents\Python_programs\microblog\app\__init__.py:70]
2019-01-19 13:15:01,176 ERROR: Exception on /notifications [GET] [in c:\users\spriy\documents\python_programs\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\spriy\documents\python_programs\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\spriy\documents\python_programs\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\spriy\documents\python_programs\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\spriy\documents\python_programs\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\spriy\documents\python_programs\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\spriy\documents\python_programs\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\spriy\documents\python_programs\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\spriy\Documents\Python_programs\microblog\app\routes.py", line 19, in notifications
    return jsonify([{
NameError: name 'jsonify' is not defined
2019-01-19 13:15:11,854 ERROR: Exception on /notifications [GET] [in c:\users\spriy\documents\python_programs\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\spriy\documents\python_programs\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\spriy\documents\python_programs\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\spriy\documents\python_programs\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\spriy\documents\python_programs\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\spriy\documents\python_programs\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\spriy\documents\python_programs\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\spriy\documents\python_programs\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\spriy\Documents\Python_programs\microblog\app\routes.py", line 19, in notifications
    return jsonify([{
NameError: name 'jsonify' is not defined
2019-01-19 13:15:21,637 ERROR: Exception on /notifications [GET] [in c:\users\spriy\documents\python_programs\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\spriy\documents\python_programs\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\spriy\documents\python_programs\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\spriy\documents\python_programs\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\spriy\documents\python_programs\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\spriy\documents\python_programs\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\spriy\documents\python_programs\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\spriy\documents\python_programs\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\spriy\Documents\Python_programs\microblog\app\routes.py", line 19, in notifications
    return jsonify([{
NameError: name 'jsonify' is not defined
2019-01-19 13:15:35,338 INFO: Microblog startup [in C:\Users\spriy\Documents\Python_programs\microblog\app\__init__.py:70]
2019-01-19 13:15:38,623 ERROR: Exception on /notifications [GET] [in c:\users\spriy\documents\python_programs\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\spriy\documents\python_programs\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\spriy\documents\python_programs\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\spriy\documents\python_programs\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\spriy\documents\python_programs\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\spriy\documents\python_programs\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\spriy\documents\python_programs\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\spriy\documents\python_programs\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\spriy\Documents\Python_programs\microblog\app\routes.py", line 19, in notifications
    return jsonify([{
NameError: name 'jsonify' is not defined
